# docker-compose.yml
version: '3.8'

services:
  headcount:
    build: .
    container_name: bus-headcount
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - CAMERA_INDEX=10
      - PYTHONUNBUFFERED=1