# docker-compose.yml
#
# Main Docker Compose file to run both the Drowsiness and HeadCount services.
# Place this file in your root project directory (e.g., 'Face sensor').
# Run with: docker-compose up --build -d

version: '3.8'

services:
  # --- Drowsiness Detection Service ---
  drowsiness-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drowsiness-monitor
    restart: unless-stopped
    privileged: true # Required for camera access
    devices:
      - /dev/video10:/dev/video10
      - /dev/galcore:/dev/galcore
      - /dev/mxc_hantro:/dev/mxc_hantro
      - /dev/mxc_hantro_vc8000e:/dev/mxc_hantro_vc8000e
    ports:
      - "5000:5000"